=  文档的标题
:hardbreaks:
:source-highlighter: coderay
:imagesdir: ./_images

== 标题二级
=== 标题三级
==== 四级标题
===== 五级标题
====== 六级标题

这是一行正文

== 2. 列表
. 有序列表
. 有序列表
. 有序列表

分隔的文字。

* 无序列表
* 无序列表
* 无序列表

== 3. 高亮代码

[source, python]
----
@requires_authorization
class SomeClass:
    pass

if __name__ == '__main__':
    # A comment
    print ('hello world')
----

[mermaid, test_img]
----
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
----

== 4. 表格

[cols="1,1,2", options="header"] 
.Applications
|===
|Name
|Category
|Description

|Firefox
|Browser
|Mozilla Firefox is an open-source web browser.
It's designed for standards compliance,
performance, portability.

|Arquillian
|Testing
|An innovative and highly extensible testing platform.
Empowers developers to easily create real, automated tests.
|===

== 5. diagrams
. absurd /əbˈsɜːd/
stupid and unreasonable, or silly in a humorous way:
* to deny them would be too obviously *absurd*.
* to acknowledge them would *condemn* the central *preoccupation* of modern society as a crime against humanity.

. brutal /ˈbruː.təl/
extremely cruel or harsh, violent, and completely without feelings
* The richest countries are the most *brutal*.